In [1]:
import numpy as np
import matplotlib.pyplot as plt
from utils.omega import Omega

In [2]:
def W(synaptic_strength_matrix):
    """
    Function W takes a synaptic strength matrix, where the element at i,j represents the strength from neuron j to i.
    It normalizes each synaptic strength by the sum of all strengths of neurons connecting to the target neuron.

    :param synaptic_strength_matrix: A square matrix representing synaptic strengths between neurons
    :return: A matrix where each strength is divided by the sum of strengths connecting to the target neuron
    """
    # Sum the strengths of neurons connecting to each target neuron (sum over rows)
    sum_strengths = np.sum(synaptic_strength_matrix, axis=0)
    
    # Avoid division by zero by replacing zeros with ones (no effect when numerator is zero)
    sum_strengths[sum_strengths == 0] = 1
    
    # Normalize each column by the sum of the column
    normalized_matrix = synaptic_strength_matrix / sum_strengths
    
    return normalized_matrix

# Example synaptic strength matrices
Jei = np.array([[0, 1, 2], [2, 0, 3], [3, 4, 0]])
Jie = np.array([[0, 2, 1], [1, 0, 4], [4, 3, 0]])
Jee = np.array([[0, 3, 1], [1, 0, 2], [2, 1, 0]])

# Apply the W function to these matrices
W_Jei = W(Jei)
W_Jie = W(Jie)
W_Jee = W(Jee)

W_Jei, W_Jie, W_Jee


(array([[0. , 0.2, 0.4],
        [0.4, 0. , 0.6],
        [0.6, 0.8, 0. ]]),
 array([[0. , 0.4, 0.2],
        [0.2, 0. , 0.8],
        [0.8, 0.6, 0. ]]),
 array([[0.        , 0.75      , 0.33333333],
        [0.33333333, 0.        , 0.66666667],
        [0.66666667, 0.25      , 0.        ]]))

In [3]:
import numpy as np

# Define the Heaviside step function
def heaviside(x):
    return np.heaviside(x, 0.5)

# Example usage
x_values = np.array([-1.5, -0.5, 0, 0.5, 1.5])
h_values = heaviside(x_values)

print(h_values)


[0.  0.  0.5 1.  1. ]


In [3]:
# Sample synaptic strength matrix and spike times/indices
synaptic_strength_matrix = np.array([[0, 1, 2], [2, 0, 3], [3, 4, 0]])

SeTimes = np.array([1, 3, 5])      # Postsynaptic spike times
SeIndices = np.array([0, 1, 2])    # Postsynaptic indices
SiTimes = np.array([0, 2, 4])      # Presynaptic spike times
SiIndices = np.array([2, 1, 0])    # Presynaptic indices

# Run the Omega function
omega_test = Omega(synaptic_strength_matrix, SeTimes, SeIndices, SiTimes, SiIndices)
print(omega_test)

[(0, 1, 2, 0, 0.3274923012311928), (0, 3, 2, 1, 0.32928698165641584), (0, 5, 2, 2, 0.0), (2, 3, 1, 1, 0.0), (2, 5, 1, 2, 0.43904930887522114), (4, 5, 0, 2, 0.49123845184678905)]
